backend:
  name: git-gateway
  branch: main

media_folder: "public/images/uploads"
public_folder: "/images/uploads"

collections:
  - name: "sections"
    label: "Home Sections"
    files:
      # ... (previous collections remain the same)

      - name: "game"
        label: "Game Section"
        file: "src/content/game.json"
        fields:
          - { label: "Title", name: "title", widget: "string" }
          - { label: "Subtitle", name: "subtitle", widget: "text" }
          - { label: "Status", name: "status", widget: "string" }
          - label: "Rewards"
            name: "rewards"
            widget: "object"
            fields:
              - { label: "Total Rewards", name: "total", widget: "string" }
              - { label: "Daily Rewards", name: "daily", widget: "string" }
          - label: "Features"
            name: "features"
            widget: "list"
            fields:
              - { label: "Title", name: "title", widget: "string" }
              - { label: "Description", name: "description", widget: "text" }
              - { label: "Icon", name: "icon", widget: "select", options: ["FaGamepad", "FaTrophy", "FaCoins"] }
          - { label: "CTA Text", name: "ctaText", widget: "string" }

      # ... (other collections remain the same)
